# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_identifier', models.TextField(db_index=True)),
                ('phrase_index', models.IntegerField()),
                ('phrase_text', models.TextField()),
                ('transliteration', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhrasePresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronounce.Phrase')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='phrase_corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronounce.PhraseCorpus'),
        ),
    ]
