# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_id', models.TextField()),
                ('english_name', models.TextField(null=True)),
                ('native_name', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='situationframelabel',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizer.Place'),
        ),
    ]
