# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_termcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.Document')),
            ],
        ),
    ]
