# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_documenttranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttopic',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
